-- MySQL Script generated by MySQL Workbench
-- Thu Sep 24 10:28:28 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Projects` (
  `project_id` VARCHAR(255) NOT NULL,
  `name` VARCHAR(60) NOT NULL,
  `Description` LONGTEXT NOT NULL,
  `ProjectLink` LONGTEXT NULL,
  `GithubREPO` LONGTEXT NULL,
  PRIMARY KEY (`project_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Softwares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Softwares` (
  `softwares_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `icon` LONGTEXT NOT NULL,
  `category` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`softwares_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Project_Photos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Project_Photos` (
  `photo_id` INT NOT NULL AUTO_INCREMENT,
  `project_ID` VARCHAR(255) NOT NULL,
  `photo_location` LONGTEXT NOT NULL,
  `headImage` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`photo_id`),
  CONSTRAINT `FK_PRJ_PHOTOS`
    FOREIGN KEY (`project_ID`)
    REFERENCES `mydb`.`Projects` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
